name: Auto-publish
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check version changes
      uses: EndBug/version-check@v1
      id: check
  latest:
    name: Publish Latest
    runs-on: ubuntu-latest
    needs: check
    if: contains(github.ref, 'master') && needs.check.outputs.changed == 'true'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        registry-url: "https://registry.npmjs.org"
    - name: Install dependencies
      run: npm install
    - name: Publish to NPM
      run: npm publish # Publish builds automatically
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  beta:
    name: Publish Beta
    runs-on: ubuntu-latest
    needs: check
    if: contains(github.ref, 'next') && needs.check.outputs.changed == 'true'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        registry-url: "https://registry.npmjs.org"
    - name: Install dependencies
      run: npm install
    - name: Publish to NPM
      run: npm publish --tag next # Publish builds automatically
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
